name: Deploy on PR comment

on:
  issue_comment:
    types: [created]

jobs:
  check_comment_and_deploy:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'deploy')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.issue.number }}/merge

    - name: Setup Google Cloud Authentication
      uses: google-github-actions/auth@v2  # Verifique se há uma versão mais recente disponível
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Google Cloud Project
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
  
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:$GITHUB_SHA
    
    - name: Deploy to GCP
      run: |
        # Comando para deploy no GCP (ajuste com seu comando específico)
        echo "Iniciando deploy..."
        # Exemplo: gcloud run deploy ....
