name: PR Comment Trigger

on:
  issue_comment:
    types:
      - created

jobs:
  comment-trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run on PR comment
      if: github.event_name == 'issue_comment' && contains(github.event.comment.body, 'teste')
      run: |
        echo "The trigger comment was found in the PR comment. Running your job now."
        run: go test -cover -race -vet=off ./...
