name: Go Cloud Run CI/CD
on:
  push:
    branches:
      - main

jobs:
  setup_build_deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Submit build to Google Cloud Build and Deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/$GCP_PROJECT/app-image
        gcloud run deploy my-app --image gcr.io/$GCP_PROJECT/app-image --platform managed --region us-central1 --allow-unauthenticated
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}